### ISSUE TITLE
[ENHANCEMENT] Deploying for production.

### ISSUE THREAD

**Issue by TeganLovesUnicorns** [technology-ebay-de/universal-react-router4#3]
Looking for advice on how to efficiently deploy this app for production. I know that this app is only a demo, but I want to make sure I know how to deploy a Universal React App for production.

Thanks in advance.

**Comment by pahund** [comment]
@flyingguitarman that's a rather broad question that's hard to answer in detail. At eBay, we have a Jenkins CI system that builds our application (Express+React+react-router4) and deploys it to our cloud infrastructure using Orlo. Your mileage will probably vary, but I can say that we didn't have any problems setting up the build and deployment jobs.
