### ISSUE TITLE
Warning on server side rendering

### ISSUE THREAD

**Issue by NithishReddy** [technology-ebay-de/universal-react-router4#4]
Hi,
I have implemented server side rending with React-Redux.
While loading page, below warning is coming on web console.
-React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client)  data-reactid="17"></div><div class="loa
 (server)  data-reactid="17"><div class="tuple-con

Any solution?

**Comment by pahund** [comment]
Hi @NithishReddy, is this a problem you get when you install this project, or rather with your own project?

**Comment by pahund** [comment]
I'm closing this for now as there is no response. Feel free to reopen.
